"""
Canonical entity names for API and KG queries. Keep in sync with kg_pipeline/src/ontology.py.
All terms must be standardized; use these when normalizing user input (e.g. conditions, symptoms).
"""
# SYNC: keep in sync with kg_pipeline/src/ontology.py CANONICAL_ENTITY_NAMES.
# This file is the server-side source of truth; ontology.py mirrors it for pipeline normalization.
CANONICAL_ENTITY_NAMES = {
    "vitamin d": "Vitamin D",
    "vitamin d3": "Vitamin D",
    "vitamin c": "Vitamin C",
    "omega-3": "Omega-3",
    "omega 3": "Omega-3",
    "type 2 diabetes": "Type 2 diabetes",
    "t2dm": "Type 2 diabetes",
    "type 2 diabetes mellitus": "Type 2 diabetes",
    "prediabetes": "Prediabetes",
    "pre diabetes": "Prediabetes",
    "pre-diabetes": "Prediabetes",
    "pre diabetic": "Prediabetes",
    "pre diabetics": "Prediabetes",
    "hypertension": "Hypertension",
    "high blood pressure": "Hypertension",
    "cardiovascular disease": "Cardiovascular disease",
    "cvds": "Cardiovascular disease",
    "mediterranean diet": "Mediterranean diet",
    "sarcopenia": "Sarcopenia",
    "osteoporosis": "Osteoporosis",
    "metformin": "Metformin",
    "mounjaro": "Mounjaro",
    "maunzaro": "Mounjaro",
    "tirzepatide": "Mounjaro",
    "aspirin": "Aspirin",
    "longevity": "longevity",
    "weight_management": "weight_management",
    "weight management": "weight_management",
    "hypertension_management": "hypertension_management",
    # Landmine diseases — canonical name variants
    "alzheimer": "Alzheimer's disease",
    "alzheimer's": "Alzheimer's disease",
    "alzheimers": "Alzheimer's disease",
    "alzheimer's disease": "Alzheimer's disease",
    "dementia": "Dementia",
    "stroke": "Stroke",
    "cerebral infarction": "Stroke",
    "brain stroke": "Stroke",
    "cerebrovascular accident": "Stroke",
    "cva": "Stroke",
    "pancreatic cancer": "Pancreatic cancer",
    "cancer of the pancreas": "Pancreatic cancer",
    "pancreas cancer": "Pancreatic cancer",
    "chronic kidney disease": "Chronic kidney disease",
    "ckd": "Chronic kidney disease",
    "kidney failure": "Chronic kidney disease",
    "renal failure": "Chronic kidney disease",
    "chronic renal disease": "Chronic kidney disease",
    "depression": "Major depressive disorder",
    "major depression": "Major depressive disorder",
    "clinical depression": "Major depressive disorder",
    "mdd": "Major depressive disorder",
    "major depressive disorder": "Major depressive disorder",
    "heart attack": "Cardiovascular disease",
    "myocardial infarction": "Cardiovascular disease",
    "mi": "Cardiovascular disease",
    "heart disease": "Cardiovascular disease",
    # ── Common Foods ──────────────────────────────────────────────────────
    "salmon": "Salmon",
    "olive oil": "Olive oil",
    "extra virgin olive oil": "Olive oil",
    "evoo": "Olive oil",
    "blueberries": "Blueberries",
    "blueberry": "Blueberries",
    "spinach": "Spinach",
    "broccoli": "Broccoli",
    "almonds": "Almonds",
    "almond": "Almonds",
    "walnuts": "Walnuts",
    "walnut": "Walnuts",
    "avocado": "Avocado",
    "green tea": "Green tea",
    "turmeric": "Turmeric",
    "garlic": "Garlic",
    "ginger": "Ginger",
    "sweet potato": "Sweet potato",
    "sweet potatoes": "Sweet potato",
    "brown rice": "Brown rice",
    "quinoa": "Quinoa",
    "oats": "Oats",
    "oatmeal": "Oats",
    "yogurt": "Yogurt",
    "yoghurt": "Yogurt",
    "kefir": "Kefir",
    "lentils": "Lentils",
    "lentil": "Lentils",
    "tomatoes": "Tomatoes",
    "tomato": "Tomatoes",
    "nuts": "Nuts",
    "seeds": "Seeds",
    "flaxseed": "Flaxseed",
    "flax seed": "Flaxseed",
    "flaxseeds": "Flaxseed",
    "chia seeds": "Chia seeds",
    "chia seed": "Chia seeds",
    "dark chocolate": "Dark chocolate",
    "citrus fruits": "Citrus fruits",
    "citrus fruit": "Citrus fruits",
    # ── Nutrients ─────────────────────────────────────────────────────────
    "vitamin a": "Vitamin A",
    "vitamin e": "Vitamin E",
    "vitamin k": "Vitamin K",
    "vitamin b6": "Vitamin B6",
    "vitamin b12": "Vitamin B12",
    "b12": "Vitamin B12",
    "cobalamin": "Vitamin B12",
    "folate": "Folate",
    "folic acid": "Folate",
    "iron": "Iron",
    "calcium": "Calcium",
    "magnesium": "Magnesium",
    "potassium": "Potassium",
    "zinc": "Zinc",
    "selenium": "Selenium",
    "dietary fiber": "Dietary fiber",
    "fiber": "Dietary fiber",
    "fibre": "Dietary fiber",
    "dietary fibre": "Dietary fiber",
    "protein": "Protein",
    "omega-6": "Omega-6",
    "omega 6": "Omega-6",
    "probiotics": "Probiotics",
    "probiotic": "Probiotics",
    "prebiotics": "Prebiotics",
    "prebiotic": "Prebiotics",
    "antioxidants": "Antioxidants",
    "antioxidant": "Antioxidants",
    "polyphenols": "Polyphenols",
    "polyphenol": "Polyphenols",
    "flavonoids": "Flavonoids",
    "flavonoid": "Flavonoids",
    "lycopene": "Lycopene",
    "curcumin": "Curcumin",
    "resveratrol": "Resveratrol",
    "lutein": "Lutein",
    "melatonin": "Melatonin",
    "tryptophan": "Tryptophan",
    "coenzyme q10": "Coenzyme Q10",
    "coq10": "Coenzyme Q10",
    # ── Dietary Patterns ──────────────────────────────────────────────────
    "dash diet": "DASH diet",
    "plant-based diet": "Plant-based diet",
    "plant based diet": "Plant-based diet",
    "vegan diet": "Vegan diet",
    "vegan": "Vegan diet",
    "vegetarian diet": "Vegetarian diet",
    "vegetarian": "Vegetarian diet",
    "ketogenic diet": "Ketogenic diet",
    "keto diet": "Ketogenic diet",
    "keto": "Ketogenic diet",
    "whole food diet": "Whole food diet",
    "anti-inflammatory diet": "Anti-inflammatory diet",
    "anti inflammatory diet": "Anti-inflammatory diet",
    # ── General Health Conditions ─────────────────────────────────────────
    "obesity": "Obesity",
    "iron-deficiency anaemia": "Iron-deficiency anaemia",
    "iron deficiency anaemia": "Iron-deficiency anaemia",
    "iron deficiency anemia": "Iron-deficiency anaemia",
    "iron-deficiency anemia": "Iron-deficiency anaemia",
    "insomnia": "Insomnia",
    "constipation": "Constipation",
    "irritable bowel syndrome": "Irritable bowel syndrome",
    "ibs": "Irritable bowel syndrome",
    "gastroesophageal reflux disease": "Gastroesophageal reflux disease",
    "gerd": "Gastroesophageal reflux disease",
    "acid reflux": "Gastroesophageal reflux disease",
    "non-alcoholic fatty liver disease": "Non-alcoholic fatty liver disease",
    "nafld": "Non-alcoholic fatty liver disease",
    "fatty liver": "Non-alcoholic fatty liver disease",
    "chronic inflammation": "Chronic inflammation",
    "oxidative stress": "Oxidative stress",
}


def normalize_entity_name(name: str) -> str:
    """Return canonical form for KG lookup. Use for conditions, symptoms, food names."""
    if not name or not isinstance(name, str):
        return name or ""
    key = name.strip().lower()
    return CANONICAL_ENTITY_NAMES.get(key) or name.strip()
