version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: health_navigation_kg
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt (RPC)
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=none # For easy development; set to neo4j/password for production
      - NEO4J_PLUGINS=["apoc"]
