"""
Ontology for the Health Navigation KG (aligned with docs/KG_SCHEMA_AND_EVIDENCE.md).
Used to drive extraction prompts and to normalize labels when ingesting into Neo4j.
"""

# Canonical node labels in Neo4j (no spaces; PascalCase)
ENTITY_TYPES = [
    "Disease",
    "Symptom",
    "Food",
    "Nutrient",
    "Drug",
    "LifestyleFactor",
    # Aging/biology (optional in first pass)
    "BodySystem",
    "AgeRelatedChange",
    "LifeStage",
    # Evidence graph (schema reserved; Study nodes not yet ingested from pipeline)
    "Study",
    # Medical KG layer
    "Biomarker",
    "ClinicalTrial",
    "Mechanism",
    "BiochemicalPathway",
    "PopulationGroup",
]

# Fast lookup set for normalize_entity_type (avoids .capitalize() destroying PascalCase)
_ENTITY_TYPES_SET = set(ENTITY_TYPES)

# Human-readable names that map to entity types (for extraction prompt and normalization)
ENTITY_TYPE_ALIASES = {
    "disease": "Disease",
    "symptom": "Symptom",
    "food": "Food",
    "nutrient": "Nutrient",
    "drug": "Drug",
    "drug/treatment": "Drug",
    "treatment": "Drug",
    "lifestyle factor": "LifestyleFactor",
    "lifestyle_factor": "LifestyleFactor",
    "lifestylefactor": "LifestyleFactor",
    "body system": "BodySystem",
    "body_system": "BodySystem",
    "bodysystem": "BodySystem",
    "age related change": "AgeRelatedChange",
    "age_related_change": "AgeRelatedChange",
    "agerelatedchange": "AgeRelatedChange",
    "life stage": "LifeStage",
    "life_stage": "LifeStage",
    "lifestage": "LifeStage",
    "study": "Study",
    # Medical KG layer aliases
    "biomarker": "Biomarker",
    "clinical trial": "ClinicalTrial",
    "clinical_trial": "ClinicalTrial",
    "clinicaltrial": "ClinicalTrial",
    "trial": "ClinicalTrial",
    "mechanism": "Mechanism",
    "biological mechanism": "Mechanism",
    "biochemical pathway": "BiochemicalPathway",
    "biochemical_pathway": "BiochemicalPathway",
    "biochemicalpathway": "BiochemicalPathway",
    "pathway": "BiochemicalPathway",
    "population group": "PopulationGroup",
    "population_group": "PopulationGroup",
    "populationgroup": "PopulationGroup",
    "population": "PopulationGroup",
    "study population": "PopulationGroup",
    # Common LLM noise types → correct mappings
    "condition": "Disease",
    "medical condition": "Disease",
    "medical_condition": "Disease",
    "health condition": "Disease",
    "health_condition": "Disease",
    "health outcome": "Disease",
    "health_outcome": "Disease",
    "healthoutcome": "Disease",
    "outcome": "Disease",
    "protein": "Nutrient",
    "amino acid": "Nutrient",
    "amino_acid": "Nutrient",
    "mineral": "Nutrient",
    "vitamin": "Nutrient",
    "supplement": "Nutrient",
    "dietary supplement": "Nutrient",
    "dietary_supplement": "Nutrient",
    "nutraceutical": "Nutrient",
    "phytochemical": "Nutrient",
    "therapy": "Drug",
    "medication": "Drug",
    "pharmaceutical": "Drug",
    "dietary pattern": "Food",
    "dietary_pattern": "Food",
    "dietarypattern": "Food",
    "diet pattern": "Food",
    "diet_pattern": "Food",
    "diet": "Food",
    "meal": "Food",
    "beverage": "Food",
    "health metric": "Biomarker",
    "health_metric": "Biomarker",
    "healthmetric": "Biomarker",
    "clinical marker": "Biomarker",
    "clinical_marker": "Biomarker",
    "lab test": "Biomarker",
    "lab_test": "Biomarker",
    "lab value": "Biomarker",
    "lab_value": "Biomarker",
    "biological marker": "Biomarker",
    "biological_marker": "Biomarker",
    "patient group": "PopulationGroup",
    "patient_group": "PopulationGroup",
    "patientgroup": "PopulationGroup",
    "study group": "PopulationGroup",
    "study_group": "PopulationGroup",
    "demographic": "PopulationGroup",
    "biological process": "Mechanism",
    "biological_process": "Mechanism",
    "biologicalprocess": "Mechanism",
    "process": "Mechanism",
    "molecular mechanism": "Mechanism",
    "molecular_mechanism": "Mechanism",
    "signaling pathway": "BiochemicalPathway",
    "signaling_pathway": "BiochemicalPathway",
    "metabolic pathway": "BiochemicalPathway",
    "metabolic_pathway": "BiochemicalPathway",
    "biological pathway": "BiochemicalPathway",
    "biological_pathway": "BiochemicalPathway",
    "gene": "Biomarker",
    "genetic factor": "Biomarker",
    "genetic_factor": "Biomarker",
    "geneticfactor": "Biomarker",
    "exercise": "LifestyleFactor",
    "physical activity": "LifestyleFactor",
    "physical_activity": "LifestyleFactor",
    "behavior": "LifestyleFactor",
    "behaviour": "LifestyleFactor",
    "organ": "BodySystem",
    "organ system": "BodySystem",
    "organ_system": "BodySystem",
}

# Allowed relationship types (predicates) for core + drug substitution
PREDICATES = [
    "PREVENTS",
    "CAUSES",
    "TREATS",
    "CONTAINS",
    "AGGRAVATES",
    "REDUCES_RISK_OF",
    "ALLEVIATES",
    "EARLY_SIGNAL_OF",
    "SUBSTITUTES_FOR",
    "COMPLEMENTS_DRUG",
    "AFFECTS",  # Food/Nutrient affects a Disease/Symptom (direction or magnitude unspecified)
]

# Aging/biology predicates (optional in first pass)
PREDICATES_AGING = [
    "PART_OF",
    "OCCURS_AT",
    "INCREASES_RISK_OF",
    "MODIFIABLE_BY",
    "EXPLAINS_WHY",
]

# Medical KG layer predicates
PREDICATES_MEDICAL = [
    "BIOMARKER_FOR",           # Biomarker → Disease
    "INCREASES_BIOMARKER",     # Food/Nutrient → Biomarker
    "DECREASES_BIOMARKER",     # Food/Nutrient → Biomarker
    "CONTRAINDICATED_WITH",    # Nutrient → Drug
    "TARGETS_MECHANISM",       # Food/Nutrient → Mechanism
    "STUDIED_IN",              # ClinicalTrial → PopulationGroup
]

ALL_PREDICATES = PREDICATES + PREDICATES_AGING + PREDICATES_MEDICAL

# Canonical entity names for normalization (variant -> canonical).
# SYNC: keep in sync with server/canonical.py CANONICAL_ENTITY_NAMES.
CANONICAL_ENTITY_NAMES = {
    "vitamin d": "Vitamin D",
    "vitamin d3": "Vitamin D",
    "vitamin c": "Vitamin C",
    "omega-3": "Omega-3",
    "omega 3": "Omega-3",
    "type 2 diabetes": "Type 2 diabetes",
    "t2dm": "Type 2 diabetes",
    "type 2 diabetes mellitus": "Type 2 diabetes",
    "prediabetes": "Prediabetes",
    "pre diabetes": "Prediabetes",
    "pre-diabetes": "Prediabetes",
    "pre diabetic": "Prediabetes",
    "pre diabetics": "Prediabetes",
    "hypertension": "Hypertension",
    "high blood pressure": "Hypertension",
    "cardiovascular disease": "Cardiovascular disease",
    "cvds": "Cardiovascular disease",
    "mediterranean diet": "Mediterranean diet",
    "sarcopenia": "Sarcopenia",
    "osteoporosis": "Osteoporosis",
    "metformin": "Metformin",
    "mounjaro": "Mounjaro",
    "maunzaro": "Mounjaro",
    "tirzepatide": "Mounjaro",
    "aspirin": "Aspirin",
    "longevity": "longevity",
    "weight_management": "weight_management",
    "weight management": "weight_management",
    "hypertension_management": "hypertension_management",
    # Landmine diseases — canonical name variants
    "alzheimer": "Alzheimer's disease",
    "alzheimer's": "Alzheimer's disease",
    "alzheimers": "Alzheimer's disease",
    "alzheimer's disease": "Alzheimer's disease",
    "dementia": "Dementia",
    "stroke": "Stroke",
    "cerebral infarction": "Stroke",
    "brain stroke": "Stroke",
    "cerebrovascular accident": "Stroke",
    "cva": "Stroke",
    "pancreatic cancer": "Pancreatic cancer",
    "cancer of the pancreas": "Pancreatic cancer",
    "pancreas cancer": "Pancreatic cancer",
    "chronic kidney disease": "Chronic kidney disease",
    "ckd": "Chronic kidney disease",
    "kidney failure": "Chronic kidney disease",
    "renal failure": "Chronic kidney disease",
    "chronic renal disease": "Chronic kidney disease",
    "depression": "Major depressive disorder",
    "major depression": "Major depressive disorder",
    "clinical depression": "Major depressive disorder",
    "mdd": "Major depressive disorder",
    "major depressive disorder": "Major depressive disorder",
    "heart attack": "Cardiovascular disease",
    "myocardial infarction": "Cardiovascular disease",
    "mi": "Cardiovascular disease",
    "heart disease": "Cardiovascular disease",
    # ── Common Foods ──────────────────────────────────────────────────────
    "salmon": "Salmon",
    "olive oil": "Olive oil",
    "extra virgin olive oil": "Olive oil",
    "evoo": "Olive oil",
    "blueberries": "Blueberries",
    "blueberry": "Blueberries",
    "spinach": "Spinach",
    "broccoli": "Broccoli",
    "almonds": "Almonds",
    "almond": "Almonds",
    "walnuts": "Walnuts",
    "walnut": "Walnuts",
    "avocado": "Avocado",
    "green tea": "Green tea",
    "turmeric": "Turmeric",
    "garlic": "Garlic",
    "ginger": "Ginger",
    "sweet potato": "Sweet potato",
    "sweet potatoes": "Sweet potato",
    "brown rice": "Brown rice",
    "quinoa": "Quinoa",
    "oats": "Oats",
    "oatmeal": "Oats",
    "yogurt": "Yogurt",
    "yoghurt": "Yogurt",
    "kefir": "Kefir",
    "lentils": "Lentils",
    "lentil": "Lentils",
    "tomatoes": "Tomatoes",
    "tomato": "Tomatoes",
    "nuts": "Nuts",
    "seeds": "Seeds",
    "flaxseed": "Flaxseed",
    "flax seed": "Flaxseed",
    "flaxseeds": "Flaxseed",
    "chia seeds": "Chia seeds",
    "chia seed": "Chia seeds",
    "dark chocolate": "Dark chocolate",
    "citrus fruits": "Citrus fruits",
    "citrus fruit": "Citrus fruits",
    # ── Nutrients ─────────────────────────────────────────────────────────
    "vitamin a": "Vitamin A",
    "vitamin e": "Vitamin E",
    "vitamin k": "Vitamin K",
    "vitamin b6": "Vitamin B6",
    "vitamin b12": "Vitamin B12",
    "b12": "Vitamin B12",
    "cobalamin": "Vitamin B12",
    "folate": "Folate",
    "folic acid": "Folate",
    "iron": "Iron",
    "calcium": "Calcium",
    "magnesium": "Magnesium",
    "potassium": "Potassium",
    "zinc": "Zinc",
    "selenium": "Selenium",
    "dietary fiber": "Dietary fiber",
    "fiber": "Dietary fiber",
    "fibre": "Dietary fiber",
    "dietary fibre": "Dietary fiber",
    "protein": "Protein",
    "omega-6": "Omega-6",
    "omega 6": "Omega-6",
    "probiotics": "Probiotics",
    "probiotic": "Probiotics",
    "prebiotics": "Prebiotics",
    "prebiotic": "Prebiotics",
    "antioxidants": "Antioxidants",
    "antioxidant": "Antioxidants",
    "polyphenols": "Polyphenols",
    "polyphenol": "Polyphenols",
    "flavonoids": "Flavonoids",
    "flavonoid": "Flavonoids",
    "lycopene": "Lycopene",
    "curcumin": "Curcumin",
    "resveratrol": "Resveratrol",
    "lutein": "Lutein",
    "melatonin": "Melatonin",
    "tryptophan": "Tryptophan",
    "coenzyme q10": "Coenzyme Q10",
    "coq10": "Coenzyme Q10",
    # ── Dietary Patterns ──────────────────────────────────────────────────
    "dash diet": "DASH diet",
    "plant-based diet": "Plant-based diet",
    "plant based diet": "Plant-based diet",
    "vegan diet": "Vegan diet",
    "vegan": "Vegan diet",
    "vegetarian diet": "Vegetarian diet",
    "vegetarian": "Vegetarian diet",
    "ketogenic diet": "Ketogenic diet",
    "keto diet": "Ketogenic diet",
    "keto": "Ketogenic diet",
    "whole food diet": "Whole food diet",
    "anti-inflammatory diet": "Anti-inflammatory diet",
    "anti inflammatory diet": "Anti-inflammatory diet",
    # ── General Health Conditions ─────────────────────────────────────────
    "obesity": "Obesity",
    "iron-deficiency anaemia": "Iron-deficiency anaemia",
    "iron deficiency anaemia": "Iron-deficiency anaemia",
    "iron deficiency anemia": "Iron-deficiency anaemia",
    "iron-deficiency anemia": "Iron-deficiency anaemia",
    "insomnia": "Insomnia",
    "constipation": "Constipation",
    "irritable bowel syndrome": "Irritable bowel syndrome",
    "ibs": "Irritable bowel syndrome",
    "gastroesophageal reflux disease": "Gastroesophageal reflux disease",
    "gerd": "Gastroesophageal reflux disease",
    "acid reflux": "Gastroesophageal reflux disease",
    "non-alcoholic fatty liver disease": "Non-alcoholic fatty liver disease",
    "nafld": "Non-alcoholic fatty liver disease",
    "fatty liver": "Non-alcoholic fatty liver disease",
    "chronic inflammation": "Chronic inflammation",
    "oxidative stress": "Oxidative stress",
    # ── Cancer ───────────────────────────────────────────────────────────────
    "breast cancer": "Breast cancer",
    "breast carcinoma": "Breast cancer",
    "breast neoplasm": "Breast cancer",
    "colorectal cancer": "Colorectal cancer",
    "colon cancer": "Colorectal cancer",
    "rectal cancer": "Colorectal cancer",
    "crc": "Colorectal cancer",
    "lung cancer": "Lung cancer",
    "non-small cell lung cancer": "Lung cancer",
    "nsclc": "Lung cancer",
    "prostate cancer": "Prostate cancer",
    "gastric cancer": "Gastric cancer",
    "stomach cancer": "Gastric cancer",
    "esophageal cancer": "Esophageal cancer",
    "ovarian cancer": "Ovarian cancer",
    "cervical cancer": "Cervical cancer",
    "endometrial cancer": "Endometrial cancer",
    "bladder cancer": "Bladder cancer",
    "kidney cancer": "Kidney cancer",
    "renal cell carcinoma": "Kidney cancer",
    "hepatocellular carcinoma": "Liver cancer",
    "liver cancer": "Liver cancer",
    "leukemia": "Leukemia",
    "lymphoma": "Lymphoma",
    "melanoma": "Melanoma",
    "glioblastoma": "Glioblastoma",
    "thyroid cancer": "Thyroid cancer",
    # ── Autoimmune ───────────────────────────────────────────────────────────
    "rheumatoid arthritis": "Rheumatoid arthritis",
    "ra": "Rheumatoid arthritis",
    "systemic lupus erythematosus": "Systemic lupus erythematosus",
    "sle": "Systemic lupus erythematosus",
    "lupus": "Systemic lupus erythematosus",
    "multiple sclerosis": "Multiple sclerosis",
    "ms": "Multiple sclerosis",
    "type 1 diabetes": "Type 1 diabetes",
    "t1dm": "Type 1 diabetes",
    "t1d": "Type 1 diabetes",
    "psoriasis": "Psoriasis",
    "psoriatic arthritis": "Psoriatic arthritis",
    "crohn's disease": "Crohn's disease",
    "crohn disease": "Crohn's disease",
    "crohns disease": "Crohn's disease",
    "ulcerative colitis": "Ulcerative colitis",
    "uc": "Ulcerative colitis",
    "celiac disease": "Celiac disease",
    "coeliac disease": "Celiac disease",
    # ── GI / Digestive (additions to existing IBS/GERD) ─────────────────────
    "peptic ulcer disease": "Peptic ulcer",
    "peptic ulcer": "Peptic ulcer",
    "functional dyspepsia": "Functional dyspepsia",
    # ── Mental Health (beyond depression) ────────────────────────────────────
    "generalized anxiety disorder": "Anxiety disorder",
    "anxiety disorder": "Anxiety disorder",
    "gad": "Anxiety disorder",
    "social anxiety": "Anxiety disorder",
    "bipolar disorder": "Bipolar disorder",
    "bipolar": "Bipolar disorder",
    "post-traumatic stress disorder": "PTSD",
    "ptsd": "PTSD",
    "schizophrenia": "Schizophrenia",
    "anorexia nervosa": "Eating disorder",
    "bulimia nervosa": "Eating disorder",
    "binge eating disorder": "Eating disorder",
    # ── Respiratory ──────────────────────────────────────────────────────────
    "chronic obstructive pulmonary disease": "COPD",
    "copd": "COPD",
    "asthma": "Asthma",
    "pulmonary fibrosis": "Pulmonary fibrosis",
    "idiopathic pulmonary fibrosis": "Pulmonary fibrosis",
    # ── Musculoskeletal ──────────────────────────────────────────────────────
    "osteoarthritis": "Osteoarthritis",
    "oa": "Osteoarthritis",
    "gout": "Gout",
    "gouty arthritis": "Gout",
    "chronic low back pain": "Back pain",
    "low back pain": "Back pain",
    # ── Eye Diseases ─────────────────────────────────────────────────────────
    "age-related macular degeneration": "Macular degeneration",
    "amd": "Macular degeneration",
    "macular degeneration": "Macular degeneration",
    "glaucoma": "Glaucoma",
    "diabetic retinopathy": "Diabetic retinopathy",
    "cataract": "Cataracts",
    "cataracts": "Cataracts",
    # ── Common Chronic ───────────────────────────────────────────────────────
    "anemia": "Anemia",
    "migraine": "Migraine",
    "migraine headache": "Migraine",
    "hypothyroidism": "Hypothyroidism",
    "hashimoto's thyroiditis": "Hypothyroidism",
    "hyperthyroidism": "Hyperthyroidism",
    "graves' disease": "Hyperthyroidism",
    "chronic insomnia": "Insomnia",
    # ── Existing Disease Dedup Fixes ─────────────────────────────────────────
    "cardiovascular diseases": "Cardiovascular disease",
    "cvd": "Cardiovascular disease",
    # ── Biomarkers ───────────────────────────────────────────────────────────
    "hba1c": "HbA1c",
    "hemoglobin a1c": "HbA1c",
    "glycated hemoglobin": "HbA1c",
    "glycated haemoglobin": "HbA1c",
    "a1c": "HbA1c",
    "ldl": "LDL cholesterol",
    "ldl cholesterol": "LDL cholesterol",
    "ldl-c": "LDL cholesterol",
    "low-density lipoprotein": "LDL cholesterol",
    "hdl": "HDL cholesterol",
    "hdl cholesterol": "HDL cholesterol",
    "hdl-c": "HDL cholesterol",
    "high-density lipoprotein": "HDL cholesterol",
    "crp": "C-reactive protein",
    "c-reactive protein": "C-reactive protein",
    "c reactive protein": "C-reactive protein",
    "hs-crp": "C-reactive protein",
    "high-sensitivity crp": "C-reactive protein",
    "egfr": "eGFR",
    "estimated glomerular filtration rate": "eGFR",
    "glomerular filtration rate": "eGFR",
    "triglycerides": "Triglycerides",
    "triglyceride": "Triglycerides",
    "tg": "Triglycerides",
    "fasting glucose": "Fasting glucose",
    "fasting blood glucose": "Fasting glucose",
    "fbg": "Fasting glucose",
    "fasting plasma glucose": "Fasting glucose",
    "blood pressure": "Blood pressure",
    "systolic blood pressure": "Systolic blood pressure",
    "sbp": "Systolic blood pressure",
    "diastolic blood pressure": "Diastolic blood pressure",
    "dbp": "Diastolic blood pressure",
    "bmi": "BMI",
    "body mass index": "BMI",
    "waist circumference": "Waist circumference",
    "homocysteine": "Homocysteine",
    "uric acid": "Uric acid",
    "ferritin": "Ferritin",
    "serum ferritin": "Ferritin",
    "vitamin d level": "Vitamin D level",
    "25-hydroxyvitamin d": "Vitamin D level",
    "25(oh)d": "Vitamin D level",
    "total cholesterol": "Total cholesterol",
    "insulin": "Fasting insulin",
    "fasting insulin": "Fasting insulin",
    "homa-ir": "HOMA-IR",
    "homa ir": "HOMA-IR",
    "hemoglobin": "Hemoglobin",
    "haemoglobin": "Hemoglobin",
    "albumin": "Albumin",
    "serum albumin": "Albumin",
    # ── Mechanisms ───────────────────────────────────────────────────────────
    "insulin resistance": "Insulin resistance",
    "insulin signaling": "Insulin signaling",
    "glucose metabolism": "Glucose metabolism",
    "lipid metabolism": "Lipid metabolism",
    "lipid peroxidation": "Lipid peroxidation",
    "endothelial dysfunction": "Endothelial dysfunction",
    "gut-brain axis": "Gut-brain axis",
    "gut brain axis": "Gut-brain axis",
    "neuroinflammation": "Neuroinflammation",
    "beta-amyloid accumulation": "Beta-amyloid accumulation",
    "amyloid": "Beta-amyloid accumulation",
    "tau phosphorylation": "Tau phosphorylation",
    "mitochondrial dysfunction": "Mitochondrial dysfunction",
    "autophagy": "Autophagy",
    "telomere shortening": "Telomere shortening",
    "dna methylation": "DNA methylation",
    "epigenetic modification": "Epigenetic modification",
    "gut microbiome modulation": "Gut microbiome modulation",
    "microbiome": "Gut microbiome modulation",
    "nf-kb signaling": "NF-kB signaling",
    "nf-kb": "NF-kB signaling",
    "ampk activation": "AMPK activation",
    "ampk": "AMPK activation",
    "sirtuin activation": "Sirtuin activation",
    "sirt1": "Sirtuin activation",
    "mtor signaling": "mTOR signaling",
    "mtor": "mTOR signaling",
    "glycemic control": "Glycemic control",
    "blood glucose regulation": "Glycemic control",
    "platelet aggregation": "Platelet aggregation",
    "angiogenesis": "Angiogenesis",
    "apoptosis": "Apoptosis",
    "immune modulation": "Immune modulation",
    "immunomodulation": "Immune modulation",
    # ── Clinical Trials ──────────────────────────────────────────────────────
    "predimed": "PREDIMED trial",
    "predimed trial": "PREDIMED trial",
    "dash": "DASH trial",
    "dash trial": "DASH trial",
    "dash-sodium": "DASH-Sodium trial",
    "lyon diet heart study": "Lyon Diet Heart Study",
    "nurses' health study": "Nurses' Health Study",
    "health professionals follow-up study": "Health Professionals Follow-up Study",
    "epic study": "EPIC study",
    "epic": "EPIC study",
    "framingham heart study": "Framingham Heart Study",
    "framingham": "Framingham Heart Study",
    "women's health initiative": "Women's Health Initiative",
    "whi": "Women's Health Initiative",
    "interheart": "INTERHEART study",
    "interheart study": "INTERHEART study",
    # ── Population Groups ────────────────────────────────────────────────────
    "postmenopausal women": "Postmenopausal women",
    "elderly adults": "Elderly adults",
    "older adults": "Elderly adults",
    "south asian adults": "South Asian adults",
    "mediterranean adults": "Mediterranean adults",
    "pregnant women": "Pregnant women",
    "children": "Children",
    "adolescents": "Adolescents",
    # ── Biochemical Pathways ─────────────────────────────────────────────────
    "glycolysis": "Glycolysis",
    "gluconeogenesis": "Gluconeogenesis",
    "fatty acid oxidation": "Fatty acid oxidation",
    "beta oxidation": "Fatty acid oxidation",
    "citric acid cycle": "Citric acid cycle",
    "krebs cycle": "Citric acid cycle",
    "tca cycle": "Citric acid cycle",
    "pentose phosphate pathway": "Pentose phosphate pathway",
    "cholesterol biosynthesis": "Cholesterol biosynthesis",
    "mevalonate pathway": "Cholesterol biosynthesis",
    "tryptophan metabolism": "Tryptophan metabolism",
    "folate metabolism": "Folate metabolism",
    "one-carbon metabolism": "One-carbon metabolism",
    "arachidonic acid pathway": "Arachidonic acid pathway",
    "prostaglandin synthesis": "Prostaglandin synthesis",
    # ── Organs / Body Systems ───────────────────────────────────────────────
    "brain": "Brain",
    "cerebrum": "Brain",
    "cerebral cortex": "Brain",
    "heart": "Heart",
    "cardiac": "Heart",
    "myocardium": "Heart",
    "lungs": "Lungs",
    "lung": "Lungs",
    "pulmonary": "Lungs",
    "liver": "Liver",
    "hepatic": "Liver",
    "kidneys": "Kidneys",
    "kidney": "Kidneys",
    "renal": "Kidneys",
    "pancreas": "Pancreas",
    "stomach": "Stomach",
    "gastric": "Stomach",
    "small intestine": "Small intestine",
    "large intestine": "Large intestine",
    "colon": "Large intestine",
    "rectum": "Large intestine",
    "esophagus": "Esophagus",
    "oesophagus": "Esophagus",
    "gastrointestinal tract": "Gastrointestinal tract",
    "gi tract": "Gastrointestinal tract",
    "digestive system": "Gastrointestinal tract",
    "digestive tract": "Gastrointestinal tract",
    "cardiovascular system": "Cardiovascular system",
    "circulatory system": "Cardiovascular system",
    "vascular system": "Cardiovascular system",
    "nervous system": "Nervous system",
    "central nervous system": "Nervous system",
    "cns": "Nervous system",
    "respiratory system": "Respiratory system",
    "immune system": "Immune system",
    "skeletal muscle": "Skeletal muscle",
    "muscle": "Skeletal muscle",
    "musculature": "Skeletal muscle",
    "bones": "Bones",
    "bone": "Bones",
    "skeletal system": "Bones",
    "skeleton": "Bones",
    "joints": "Joints",
    "joint": "Joints",
    "articular": "Joints",
    "skin": "Skin",
    "dermis": "Skin",
    "epidermis": "Skin",
    "eyes": "Eyes",
    "eye": "Eyes",
    "retina": "Eyes",
    "thyroid gland": "Thyroid gland",
    "thyroid": "Thyroid gland",
    "breast": "Breast",
    "mammary gland": "Breast",
    "prostate": "Prostate",
    "prostate gland": "Prostate",
    "bladder": "Bladder",
    "urinary bladder": "Bladder",
    "ovaries": "Ovaries",
    "ovary": "Ovaries",
    "uterus": "Uterus",
    "womb": "Uterus",
    "cervix": "Cervix",
    "spinal cord": "Spinal cord",
    "spine": "Spinal cord",
    "blood": "Blood",
    "hematologic system": "Blood",
    "haematologic system": "Blood",
    "adrenal glands": "Adrenal glands",
    "adrenal": "Adrenal glands",
}


def normalize_entity_name(name: str, _entity_type: str = "") -> str:
    """Map entity name to canonical form when possible (e.g. Vitamin D, Type 2 diabetes)."""
    if not name or not isinstance(name, str):
        return name or ""
    key = name.strip().lower()
    return CANONICAL_ENTITY_NAMES.get(key) or name.strip()


def normalize_entity_name_for_merge(name: str) -> str:
    """Return lowercased name for MERGE key to prevent case-sensitive duplicates.
    Always lowercases; the display_name property preserves the original casing."""
    canonical = normalize_entity_name(name)
    return canonical.lower() if canonical else ""


def normalize_entity_type(raw: str) -> str:
    """Map extraction output to canonical entity label (Neo4j node label)."""
    if not raw or not isinstance(raw, str):
        return "Thing"
    trimmed = raw.strip()
    # If already a valid entity type (e.g. LLM returned "AgeRelatedChange"), use it directly
    if trimmed in _ENTITY_TYPES_SET:
        return trimmed
    key = trimmed.replace(" ", "_").replace("-", "_").lower()
    if key in ENTITY_TYPE_ALIASES:
        return ENTITY_TYPE_ALIASES[key]
    # Fallback: capitalize first letter (preserves PascalCase unlike .capitalize())
    cleaned = trimmed.replace(" ", "_").replace("/", "_")
    return cleaned[0].upper() + cleaned[1:] if cleaned else "Thing"


def normalize_predicate(raw: str) -> str:
    """Map extraction output to canonical predicate (Neo4j relationship type)."""
    if not raw or not isinstance(raw, str):
        return "RELATES_TO"
    p = raw.strip().upper().replace(" ", "_").replace("-", "_")
    return p if p in ALL_PREDICATES else "RELATES_TO"  # Fix: was returning p in both branches (no-op)


def get_ontology_prompt_section(include_aging: bool = True) -> str:
    """Return the ontology section for the extraction prompt (entity types + relationship types).
    When include_aging=True, BodySystem, AgeRelatedChange, LifeStage and aging predicates are included (docs/AGING_AND_HUMAN_BIOLOGY.md).
    Always includes medical KG layer types (Biomarker, Mechanism, ClinicalTrial, etc.).
    """
    entity_list = "\n".join(f"- {t}" for t in (ENTITY_TYPES if include_aging else ENTITY_TYPES[:6]))
    preds = ALL_PREDICATES if include_aging else PREDICATES
    pred_list = "\n".join(f"- {p}" for p in preds)
    return f"""
Target Entity Types (use exactly these labels):
{entity_list}

Target Relationship Types (use exactly these; one per triple):
{pred_list}

Return ONLY triples whose subject_type and object_type are from the Entity Types list and whose predicate is from the Relationship Types list.
If the text discusses aging, life stage, body systems, or modifiable risk, use types like AgeRelatedChange, LifeStage, BodySystem and predicates like PART_OF, OCCURS_AT, INCREASES_RISK_OF, MODIFIABLE_BY, EXPLAINS_WHY where supported.
For early signals: use Symptom -EARLY_SIGNAL_OF-> Disease when the text describes early signs/symptoms of a disease; use ALLEVIATES (food/nutrient reduces symptom) and AGGRAVATES (food/nutrient worsens symptom) so we can recommend "foods that reduce" vs "foods to avoid".

Medical KG extraction rules:
- When the text discusses biomarkers (HbA1c, LDL, CRP, eGFR, triglycerides, fasting glucose):
  Extract: Food/Nutrient -INCREASES_BIOMARKER/DECREASES_BIOMARKER-> Biomarker
  Extract: Biomarker -BIOMARKER_FOR-> Disease
- When the text discusses biological mechanisms (inflammation, oxidative stress, insulin resistance):
  Extract: Food/Nutrient -TARGETS_MECHANISM-> Mechanism
  Extract: Mechanism -CAUSES/INCREASES_RISK_OF-> Disease
- When the text discusses drug-nutrient interactions or contraindications:
  Extract: Nutrient -CONTRAINDICATED_WITH-> Drug (with context explaining why)
- When the text references a specific named clinical trial (e.g. PREDIMED, DASH):
  Extract: ClinicalTrial -STUDIED_IN-> PopulationGroup
- When the text discusses biochemical pathways (glucose metabolism, lipid metabolism):
  Extract: Food/Nutrient -TARGETS_MECHANISM-> BiochemicalPathway
"""
